[build-system]
requires = [
    "setuptools",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "diffusion-model"
version = "0.5"
dependencies = [
    "matplotlib",
    "mpl_ascii",
    "numpy",
]

[tool.setuptools]
py-modules = ["diffusion_model"]
